#ifndef COCO_NAMES_H
#define COCO_NMAES_H

char *coco_names[]={
		(char*)"person",
		(char*)"bicycle",
		(char*)"car",
		(char*)"motorbike",
		(char*)"aeroplane",
		(char*)"bus",
		(char*)"train",
		(char*)"truck",
		(char*)"boat",
		(char*)"traffic light",
		(char*)"fire hydrant",
		(char*)"stop sign",
		(char*)"parking meter",
		(char*)"bench",
		(char*)"bird",
		(char*)"cat",
		(char*)"dog",
		(char*)"horse",
		(char*)"sheep",
		(char*)"cow",
		(char*)"elephant",
		(char*)"bear",
		(char*)"zebra",
		(char*)"giraffe",
		(char*)"backpack",
		(char*)"umbrella",
		(char*)"handbag",
		(char*)"tie",
		(char*)"suitcase",
		(char*)"frisbee",
		(char*)"skis",
		(char*)"snowboard",
		(char*)"sports ball",
		(char*)"kite",
		(char*)"baseball bat",
		(char*)"baseball glove",
		(char*)"skateboard",
		(char*)"surfboard",
		(char*)"tennis racket",
		(char*)"bottle",
		(char*)"wine glass",
		(char*)"cup",
		(char*)"fork",
		(char*)"knife",
		(char*)"spoon",
		(char*)"bowl",
		(char*)"banana",
		(char*)"apple",
		(char*)"sandwich",
		(char*)"orange",
		(char*)"broccoli",
		(char*)"carrot",
		(char*)"hot dog",
		(char*)"pizza",
		(char*)"donut",
		(char*)"cake",
		(char*)"chair",
		(char*)"sofa",
		(char*)"pottedplant",
		(char*)"bed",
		(char*)"diningtable",
		(char*)"toilet",
		(char*)"tvmonitor",
		(char*)"laptop",
		(char*)"mouse",
		(char*)"remote",
		(char*)"keyboard",
		(char*)"cell phone",
		(char*)"microwave",
		(char*)"oven",
		(char*)"toaster",
		(char*)"sink",
		(char*)"refrigerator",
		(char*)"book",
		(char*)"clock",
		(char*)"vase",
		(char*)"scissors",
		(char*)"teddy bear",
		(char*)"hair drier",
		(char*)"toothbrush"
};

#endif
